### PR TITLE
Issues 46 and 48: Add the "-scope" parameter and fix the reader-groups issue

### LINKED ISSUE #46: Scope to be passed in via command line argument
Currently, the scope is hard coded it as 'scope'.

Please parameterize it to allow scope can be any name via command line argument (just as how it handles stream currently).

### PR DESCRIPTION
**Pull request by kmgowda**
**Change log description**  
The "-scope"  parameter is added so that use the pass the name of the scope ; If no scope name is supplied then default scope name "Scope" is used. A different reader group names are used in case of end to end latency. 
The data format is changed from String to Byte Array to avoid the string serialization by Pravega.

**Purpose of the change**
Fixes #46, #48 

**What the code does**
By adding the "-scope" parameter , enabled the user to supply the custom scope names.
Currently reader group delete throws an error in-case of  reader group does not exists; hence different reader groups named used in case of end to end latency.

**How to verify it**
Tested the benchmark tool with and without "-scope" parameter.
Tested the end to end latency repeatedly on bare metal setup and standalone execution.

### CODE REVIEW

File: src/main/java/io/pravega/perf/PerfStats.java [hunk 1]
```diff
@@ -212,19 +212,7 @@ private long windowTimeMS(long time) {
         long totalLatency;
         long maxLatency;
         long totalBytes;
-        ArrayList<LatencyRange> latencyRanges;
```
Comment (tkaitchuck) [inline src/main/java/io/pravega/perf/PerfStats.java]: I'm not sure this change is needed.

File: src/main/java/io/pravega/perf/PravegaStreamHandler.java [hunk 2]
```diff
@@ -135,15 +141,25 @@ void recreate() throws InterruptedException, ExecutionException, TimeoutExceptio
...
             rdGroup.resetReaderGroup(rdGrpConfig);
         }
         return rdGroup;
     }
+
+    void deleteReaderGroup() {
+        try {
+            readerGroupManager.deleteReaderGroup(rdGrpName);
+        } catch (InvalidStreamException e) {
+            System.out.println("Reader Group is already deleted");
```
Comment (tkaitchuck) [inline src/main/java/io/pravega/perf/PravegaStreamHandler.java]: In the absence of any context this message would be confusing. Perhaps: "Cannot delete reader group X because it is already deleted" would be better.

File: src/main/java/io/pravega/perf/ReaderWorker.java [hunk 3]
```diff
@@ -54,20 +56,25 @@ private Performance createBenchmark() {
 
     @Override
     public Void call() throws InterruptedException, ExecutionException, IOException {
-        perf.benchmark();
+        try {
+            perf.benchmark();
+        } catch (Exception e) {
+            e.printStackTrace();
```
Comment (tkaitchuck) [inline src/main/java/io/pravega/perf/ReaderWorker.java]: What's the point of printing the stack trace only to rethrow the same one?

File: src/main/java/io/pravega/perf/WriterWorker.java [hunk 4]
```diff
@@ -107,7 +107,12 @@ private Performance createBenchmark() {
 
     @Override
     public Void call() throws InterruptedException, ExecutionException, IOException {
-        perf.benchmark();
+        try {
+            perf.benchmark();
+        } catch (Exception e) {
+            e.printStackTrace();
```
Comment (tkaitchuck) [inline src/main/java/io/pravega/perf/WriterWorker.java]: Again, why print if it's just going to be rethrown?

File: src/main/java/io/pravega/perf/PerfStats.java (hunk 1 above)
Comment (kmgowda) [reply src/main/java/io/pravega/perf/PerfStats.java]: this is as part of code cleanup.. earlier i had class LatencyRange , now its replaced by Array.

File: src/main/java/io/pravega/perf/ReaderWorker.java (hunk 3 above)
Comment (kmgowda) [reply src/main/java/io/pravega/perf/ReaderWorker.java]: actually the callables (even though i have them printing in PravegaperTest class) are not printing the stack, so, this is alternative

File: src/main/java/io/pravega/perf/WriterWorker.java (hunk 4 above)
Comment (kmgowda) [reply src/main/java/io/pravega/perf/WriterWorker.java]: only for debugging purpose.

File: src/main/java/io/pravega/perf/PravegaStreamHandler.java (hunk 2 above)
Comment (kmgowda) [reply src/main/java/io/pravega/perf/PravegaStreamHandler.java]: yes.. its changed now..
